### ISSUE TITLE
能否更新下代码到maven仓库？

### ISSUE THREAD

**Issue by YaoZihuan** [palominolabs/url-builder#10]
能否更新下代码到maven仓库？

**Comment by marshallpierce** [comment]
Sorry, I only read English, but I'm guessing that you're wondering how to use this via Maven. The package is released in [bintray](https://bintray.com/marshallpierce/maven/com.palominolabs.http%3Aurl-builder) and linked to [jcenter](https://bintray.com/bintray/jcenter). See the "Set me up" button.
