### ISSUE TITLE
update license version

### ISSUE THREAD

**Issue by apotheon** [palominolabs/url-builder#12]
I see this project uses the Copyfree Open Innovation License.  You may want to
update the license to the 0.6 version.  The 0.6 version has been improved for
legal clarity, and has been reviewed by an attorney.

* [license information](https://coil.apotheon.org/)
* [COIL-0.6 license text](https://coil.apotheon.org/plaintext/00.6.txt)

**Comment by marshallpierce** [comment]
Done, thanks.

**Comment by apotheon** [comment]
I'm glad you updated to 1.0, which was added to SPDX after I opened this issue.  Good job!
