### ISSUE TITLE
Version 1.1.4 maven artifact is not compatible with java 8

### ISSUE THREAD

**Issue by edrik** [palominolabs/url-builder#13]
Getting this when running on Java 8:
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
	at com.palominolabs.http.url.PercentEncoder.encode(PercentEncoder.java:79)
	at com.palominolabs.http.url.PercentEncoder.encode(PercentEncoder.java:119)
	at com.palominolabs.http.url.UrlBuilder.toUrlString(UrlBuilder.java:337)
	...
```
Looks like the jar is not built with java 8, causing it to compile with the overridden method signatures ([CharBuffer.clear](https://docs.oracle.com/javase/9/docs/api/java/nio/CharBuffer.html#clear--) return type) introduced by java 9.

The issue apparently appears even with source and target 8 or lower in compilation parameters. But not familiar with the Kotlin related parts of the Gradle build, so can't really tell if it adds any additional `releases` compile flags when building and packaging the jar for maven.

For the code to remain compatible, a solution is to cast `CharBuffer` instances to `Buffer` before calling the methods in question.
And this would apply to all the similar places int he code that call the incompatible methods on `CharBuffer` or `ByteBuffer`.

**Comment by marshallpierce** [comment]
You are correct.

Built with java 8 as the shell's active JVM:

```
      48: invokevirtual #16                 // Method java/nio/CharBuffer.clear:()Ljava/nio/Buffer;
```

And with Java 19:

```
      48: invokevirtual #71                 // Method java/nio/CharBuffer.clear:()Ljava/nio/CharBuffer;
```

However, after switching to using Gradle's toolchain support, we're back to:

```
      48: invokevirtual #16                 // Method java/nio/CharBuffer.clear:()Ljava/nio/Buffer;
```

Fix forthcoming in https://github.com/palominolabs/url-builder/pull/14.

**Comment by marshallpierce** [comment]
1.1.5 should be making its way through the interwebs now.

**Comment by edrik** [comment]
Nice, that was quick!
And confirmed that 1.1.5 works now :+1:

**Comment by marshallpierce** [comment]
Gotta try to keep my OSS bug count at 0 ;)
